project:
  type: website

website:
  title: "Toby Driscoll"
  site-url: https://tobydriscoll.net
  navbar:
    left:
      - href: cv.qmd
        text: CV
      - text: Publications
        menu:
          - href: "cv.html#sec-publications"
            text: List
          - books.qmd
          - href: https://scholar.google.com/citations?user=V2c1tmAAAAAJ&hl=en
            text: Google Scholar
          - href: https://www.zotero.org/tobydriscoll
            text: Zotero library
          - href: https://arxiv.org/a/driscoll_t_1.html
            text: arXiv page
      - projects.qmd
      - blog.qmd
  open-graph: true
  favicon: _media/favicon.ico

format:
  html:
    theme: 
      light: zephyr
      dark: darkly
    respect-user-color-scheme: true
    # css: styles.css
    toc: true



